name: Benchmark

on:
  push:
    branches:    
      - main

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build . --file Dockerfile --tag adbayb/language-benchmarks:latest
      - name: Run
        run: docker run adbayb/language-benchmarks:latest
